### PR TITLE
Prepare release 2.1.0

### PR DESCRIPTION
**Pull request by gwarf**
- Only release on new tags, not on push to main
- Update building and releasing instructions
- Package community files
- Build RPMs using the Makefile
- Bump version and changelog for 2.1.0

### CODE REVIEW

**Review by enolfc — COMMENTED** [review]
Will there be another PR with the actual 2.1 schema in place?

**Comment by gwarf** [comment]
Good question, the GLUE 2.1 schema is still not approved, so not sure if we can/should release it.
What do you think @paolini78 ?

**Comment by paolini78** [comment]
I'd suggest to move on. The Glue 2.1 was practically agreed and at the moment we really don't know when they publish it, we cannot be blocked by this situation.

**Comment by enolfc** [comment]
I meant: where there will be changes to [glue-schema](https://github.com/EGI-Federation/glue-schema)/[etc](https://github.com/EGI-Federation/glue-schema/tree/main/etc)/[ldap](https://github.com/EGI-Federation/glue-schema/tree/main/etc/ldap)/[schema](https://github.com/EGI-Federation/glue-schema/tree/main/etc/ldap/schema)/GLUE20.schema ? or a new file `GLUE21.schema` ? I would expect these changes to somehow be linked to this PR

**Comment by gwarf** [comment]
This PR was only about packaging automatically what was available, maybe you got confused by the name of the version, but it is not meant to do anything specific to GLUE 2.1.
We can certainly add this in a dedicated PR.

**Review by enolfc — APPROVED** [review]
LGTM!

**Comment by gwarf** [comment]
Packages have been built: https://github.com/EGI-Federation/glue-schema/releases/tag/v2.1.0

**Pull request merged**
